language: ruby
rvm:
 - 2.2   
branches:
except:
 - master
 - experiment
services:
 - memcached
env:
 - DB=test/integration/books.sqlite && MCACHE=localhost:11211  
before_script:
  - touch $DB && ruby test/integration/setup_datastores.rb
script: 
  - rspec test/integration/rspec_*.rb